# Jekyll configuration for GitHub Pages
title: Chomp
description: The beginning of a new adventure.
author: Dipesh V Patel
email: your.email@example.com
url: https://dipeshvpatel.github.io
baseurl: ""

# Theme
theme: minima

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files/directories from processing
exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
